In [33]:
import pandas as pd

In [34]:
base_path = "../../../assets/test_results/"
# df_aia=pd.read_csv(base_path + "sdofmv2-aia-test-results.csv")
df_all = pd.read_csv(base_path + "sdofmv2-all-test-results-final.csv")
df_denoise = pd.read_csv(base_path + "sdofmv2-all-test-results-denoise.csv")
# df_hmi=pd.read_csv(base_path + "sdofmv2-hmi-test-results.csv")
df_all_large=pd.read_csv(base_path + "sdofmv2-large-all-test-results.csv")
df_all_small=pd.read_csv(base_path + "sdofmv2-small-all-test-results.csv")

In [35]:
# Add source labels
# df_aia["dataset"] = "aia"
df_all["dataset"] = "all"
df_denoise["dataset"] = "all_denoise"
# df_hmi["dataset"] = "hmi"
df_all_large["dataset"] = "all_large"
df_all_small["dataset"] = "all_small"

# Combine
df_combined_all = pd.concat(
    [df_all, df_denoise, df_all_large, df_all_small],
    ignore_index=True
)

# Keep only relevant columns
# metrics = ["rmse_intensity", "r2_score", "pixel_correlation"]

df_long = df_combined_all.melt(
    id_vars=["dataset", "channel"],
    # value_vars=metrics,
    var_name="metric",
    value_name="value"
)

print(df_long.head())

  dataset channel    metric     value
0     all    131A  mse_norm  0.118978
1     all   1600A  mse_norm  0.386497
2     all   1700A  mse_norm  0.283360
3     all    171A  mse_norm  0.130923
4     all    193A  mse_norm  0.067773

In [36]:
df_long

       dataset channel                    metric     value
0          all    131A                  mse_norm  0.118978
1          all   1600A                  mse_norm  0.386497
2          all   1700A                  mse_norm  0.283360
3          all    171A                  mse_norm  0.130923
4          all    193A                  mse_norm  0.067773
..         ...     ...                       ...       ...
475  all_small    335A  pixel_correlation_unnorm  0.942007
476  all_small     94A  pixel_correlation_unnorm  0.878255
477  all_small      Bx  pixel_correlation_unnorm  0.064105
478  all_small      By  pixel_correlation_unnorm  0.027065
479  all_small      Bz  pixel_correlation_unnorm  0.382941

[480 rows x 4 columns]

In [37]:
aia_chan = ['131A', '1600A', '1700A', '171A', '193A', '211A', '304A', '335A', '94A']

mse_table = (
    df_long[df_long["metric"] == "mse_norm"]
    .pivot(
        index="channel",
        columns="dataset",
        values="value"
    )
)
mse_table.loc["Mean"] = mse_table.mean()
mse_table = mse_table.round(3)

rmse_table = (
    df_long[df_long["metric"] == "rmse_intensity_norm"]
    .pivot(
        index="channel",
        columns="dataset",
        values="value"
    )
)
rmse_table.loc["Mean"] = rmse_table.mean()
rmse_table = rmse_table.round(3)

mae_table = (
    df_long[df_long["metric"] == "mse_norm"]
    .pivot(
        index="channel",
        columns="dataset",
        values="value"
    )
)
mae_table.loc["Mean"] = mae_table.mean()
mae_table = mae_table.round(3)

r2_table = (
    df_long[df_long["metric"] == "r2_score_norm"]
    .pivot(
        index="channel",
        columns="dataset",
        values="value"
    )
)
r2_table.loc["Mean"] = r2_table.mean()
r2_table = r2_table.round(3)

corr_table = (
    df_long[df_long["metric"] == "pixel_correlation_norm"]
    .pivot(
        index="channel",
        columns="dataset",
        values="value"
    )
)
corr_table.loc["Mean"] = corr_table.mean()
corr_table = corr_table.round(3)

In [38]:
mse_table

dataset    all  all_denoise  all_large  all_small
channel
131A     0.119        0.041      0.082      0.094
1600A    0.386        0.139      0.366      0.396
1700A    0.283        0.080      0.269      0.213
171A     0.131        0.041      0.139      0.103
193A     0.068        0.018      0.099      0.079
211A     0.062        0.013      0.052      0.050
304A     0.248        0.095      0.185      0.249
335A     0.079        0.026      0.059      0.059
94A      0.110        0.036      0.083      0.102
Bx       0.878        0.439      0.758      0.867
By       0.867        0.431      0.805      0.932
Bz       0.799        0.444      0.725      0.872
Mean     0.336        0.150      0.302      0.335

In [39]:
rmse_table

dataset    all  all_denoise  all_large  all_small
channel
131A     0.343        0.203      0.286      0.306
1600A    0.620        0.371      0.601      0.629
1700A    0.531        0.282      0.517      0.460
171A     0.360        0.200      0.373      0.320
193A     0.259        0.133      0.313      0.280
211A     0.248        0.112      0.226      0.223
304A     0.498        0.307      0.430      0.499
335A     0.280        0.158      0.240      0.243
94A      0.323        0.187      0.288      0.319
Bx       0.936        0.659      0.869      0.929
By       0.930        0.653      0.895      0.964
Bz       0.891        0.662      0.849      0.932
Mean     0.518        0.327      0.491      0.509

In [40]:
r2_table

dataset    all  all_denoise  all_large  all_small
channel
131A     0.858        0.947      0.897      0.881
1600A    0.602        0.858      0.629      0.590
1700A    0.707        0.918      0.723      0.780
171A     0.848        0.954      0.829      0.881
193A     0.918        0.978      0.871      0.899
211A     0.896        0.979      0.912      0.925
304A     0.719        0.890      0.788      0.712
335A     0.861        0.942      0.871      0.895
94A      0.823        0.930      0.826      0.794
Bx       0.217        0.611      0.325      0.228
By       0.228        0.619      0.285      0.171
Bz       0.260        0.591      0.329      0.192
Mean     0.662        0.851      0.690      0.662

In [41]:
corr_table

dataset    all  all_denoise  all_large  all_small
channel
131A     0.945        0.973      0.953      0.949
1600A    0.858        0.926      0.861      0.841
1700A    0.918        0.958      0.911      0.915
171A     0.943        0.977      0.948      0.955
193A     0.974        0.989      0.969      0.976
211A     0.977        0.990      0.971      0.979
304A     0.896        0.943      0.897      0.875
335A     0.952        0.970      0.955      0.953
94A      0.934        0.965      0.931      0.925
Bx       0.643        0.781      0.635      0.573
By       0.646        0.786      0.622      0.556
Bz       0.640        0.767      0.630      0.578
Mean     0.861        0.919      0.857      0.840