In [32]:
import pandas as pd

In [33]:
base_path = "../../../../assets/ds_results/missing_channel/"
columns = ["wavelength", "mse", "rmse_intensity", "mae", "r2_score"]
df_aia = pd.read_csv(base_path + "missing_channel_test_sdofmv2-aia.csv", usecols=columns)
df_all = pd.read_csv(base_path + "missing_channel_test_sdofmv2-all.csv", usecols=columns)
df_all_zero = pd.read_csv(base_path + "missing_channel_test_sdofmv2-all-zeroshot.csv", usecols=columns)
df_hmi = pd.read_csv(base_path + "missing_channel_test_sdofmv2-hmi-log.csv", usecols=columns)

In [34]:
def modifying_df(df):
    df.set_index("wavelength", inplace=True)
    df.loc["mean"] = df.mean()
    df = df.rename(columns={
        "mse": "MSE",
        "rmse_intensity": "RMSE",
        "mae": "MAE",
        "r2_score": "R²"
    })
    df = df[["MSE", "RMSE", "MAE", "R²"]]
    return df

In [35]:
df_aia = modifying_df(df_aia)

In [36]:
# columns_order = ["mse", "rmse_intensity", "mae", "r2_score"]
df_aia

                    MSE       RMSE        MAE        R²
wavelength
131A           0.656871   0.647352   0.298000  0.966207
1600A         16.060977   3.922378   1.992090  0.987177
1700A       1772.118856  41.758273  21.244044  0.990301
171A         117.592083  10.644300   5.870553  0.989680
193A         206.080817  14.171447   5.430052  0.982176
211A          26.243277   4.954228   1.416375  0.962778
304A          38.879781   6.033281   3.118222  0.957436
335A           0.961393   0.529162   0.237948  0.908143
94A            0.068438   0.117710   0.046726  0.934296
mean         242.073610   9.197570   4.406001  0.964244

In [37]:
df_all = modifying_df(df_all)

In [38]:
df_all

                     MSE        RMSE        MAE        R²
wavelength
131A            0.800908    0.756396   0.343424  0.956718
1600A          22.965963    4.753250   2.437316  0.981642
1700A        2532.695566   50.204977  25.391780  0.986136
171A          168.030328   12.812565   6.965167  0.985238
193A          322.260171   17.682591   6.685494  0.972184
211A           35.502104    5.791545   1.638891  0.949843
304A           60.414223    7.631798   3.932507  0.933609
335A            1.018576    0.576699   0.256126  0.892321
94A             0.070781    0.124918   0.049961  0.928903
Bx          12878.785217  108.666175  28.920146 -5.319294
By          14393.481656  114.205845  29.627494 -6.006977
Bz             32.445043    5.596753   1.839840  0.337341
mean         2537.372545   27.400293   9.007345 -0.200195

In [39]:
df_hmi = modifying_df(df_hmi)

In [40]:
df_hmi

                    MSE       RMSE        MAE        R²
wavelength
Bx          2743.624443  49.150956  19.344139 -0.293408
By          1992.164840  42.884120  19.250989  0.047028
Bz            42.296150   6.430692   2.095401  0.121548
mean        1592.695144  32.821923  13.563510 -0.041611

In [41]:
df_all_zero = modifying_df(df_all_zero)

In [42]:
df_all_zero

                     MSE          RMSE         MAE            R²
wavelength
131A        2.521611e+00      1.381641    0.894565  8.405900e-01
1600A       5.355343e+01      7.057470    4.306136  9.571383e-01
1700A       5.927866e+03     74.762982   45.141840  9.675474e-01
171A        1.148890e+03     29.983293   20.066490  8.988135e-01
193A        1.430619e+03     33.003514   16.597709  8.749090e-01
211A        1.177925e+02     10.024267    3.874006  8.409735e-01
304A        1.445868e+02     11.185344    6.993400  8.404070e-01
335A        1.388206e+00      0.837837    0.479184  7.526940e-01
94A         9.910914e-02      0.216629    0.134576  7.693703e-01
Bx          1.628662e+09  30788.425441  595.741313 -7.919694e+05
By          1.307784e+11  96893.433918  964.992653 -5.467051e+07
Bz          1.019919e+02      9.985471    2.827647 -1.268234e+00
mean        1.103392e+10  10655.024817  138.504127 -4.621872e+06

In [43]:
df_all_combine = pd.concat([df_all, df_all_zero], axis=1)

In [44]:
df_all_combine.drop(["mean", "Bx", "By", "Bz"], axis=0, inplace=True)
df_all_combine.loc["mean"] = df_all_combine.mean()

In [45]:
df_all_combine

,MSE,RMSE,MAE,R²,MSE,RMSE,MAE,R²
wavelength,,,,,,,,
131A,0.800908,0.756396,0.343424,0.956718,2.521611,1.381641,0.894565,0.840590
1600A,22.965963,4.753250,2.437316,0.981642,53.553432,7.057470,4.306136,0.957138
1700A,2532.695566,50.204977,25.391780,0.986136,5927.866161,74.762982,45.141840,0.967547
171A,168.030328,12.812565,6.965167,0.985238,1148.890040,29.983293,20.066490,0.898813
193A,322.260171,17.682591,6.685494,0.972184,1430.619152,33.003514,16.597709,0.874909
211A,35.502104,5.791545,1.638891,0.949843,117.792493,10.024267,3.874006,0.840973
304A,60.414223,7.631798,3.932507,0.933609,144.586765,11.185344,6.993400,0.840407
335A,1.018576,0.576699,0.256126,0.892321,1.388206,0.837837,0.479184,0.752694
94A,0.070781,0.124918,0.049961,0.928903,0.099109,0.216629,0.134576,0.769370
mean,349.306513,11.148304,5.300074,0.954066,980.812997,18.716997,10.943101,0.860271