In [ ]:
import pandas as pd

In [ ]:
base_path = "../../../../assets/ds_results/missing_channel/"
df_aia = pd.read_csv(base_path + "missing_channel_test_sdofmv2-aia.csv")
df_all = pd.read_csv(base_path + "missing_channel_test_sdofmv2-all.csv")
df_hmi = pd.read_csv(base_path + "missing_channel_test_sdofmv2-hmi-log.csv")

In [ ]:
columns = ["mse", "rmse_intensity", "mae", "r2_score"]
df_aia[columns]

           mse  rmse_intensity        mae  r2_score
0     0.656871        0.647352   0.298000  0.966207
1    16.060977        3.922378   1.992090  0.987177
2  1772.118856       41.758273  21.244044  0.990301
3   117.592083       10.644300   5.870553  0.989680
4   206.080817       14.171447   5.430052  0.982176
5    26.243277        4.954228   1.416375  0.962778
6    38.879781        6.033281   3.118222  0.957436
7     0.961393        0.529162   0.237948  0.908143
8     0.068438        0.117710   0.046726  0.934296

In [ ]:
df_aia.mean(axis=0)

In [7]:
df_all[columns]

             mse  rmse_intensity        mae  r2_score
0       0.807642        0.762001   0.345211  0.956161
1      23.217630        4.778565   2.450979  0.981441
2    2550.418315       50.383967  25.491100  0.986039
3     167.021293       12.786325   6.949410  0.985320
4     323.163040       17.727881   6.679241  0.972083
5      34.304392        5.741523   1.637145  0.950461
6      57.115227        7.443023   3.831846  0.937295
7       1.015380        0.575001   0.255768  0.893033
8       0.070858        0.125175   0.050083  0.928572
9   12523.313935      107.732600  28.886469 -5.279627
10  14473.381905      115.695383  29.666196 -6.150029
11     32.402664        5.589684   1.835927  0.340007

In [8]:
df_hmi[columns]

           mse  rmse_intensity        mae  r2_score
0  2743.624443       49.150956  19.344139 -0.293408
1  1992.164840       42.884120  19.250989  0.047028
2    42.296150        6.430692   2.095401  0.121548